from pipelines.kfp_components.ml_components.train import train
from pipelines.kfp_components.ml_components.evaluate import evaluate
from pipelines.kfp_components.ml_components.predict import predict
from pipelines.kfp_components.ml_components.preprocess import preprocess_predict